### ISSUE TITLE
does not correctly count the number of rafts that can be placed on the disk

### ISSUE THREAD

**Issue by HVNC1** [gabyvespasiano/gabyvespasiano.github.io#1]
![image](https://user-images.githubusercontent.com/95166695/235416780-be0cf30e-2b85-4693-a2a7-b974e83c1232.png)
does not correctly count the number of plots that can be placed on the disk
could you please review this. i was doing the calculation for compressed sections k30 with compression ratio c8
after that I was easily able to fit a few more plots in there
are you using reference sizes from gigahorse or bladebit as they are different
![image](https://user-images.githubusercontent.com/95166695/235416835-1b2d60a5-0ecd-4699-883c-9c2a5d4f1081.png)

**Comment by gabyvespasiano** [comment]
im using this values , if you have better i fix
const plotSizes = {
  "GB": {
    "NA" : {"k30": 25.662,"k31": 53.687,"k32": 108.877, "k33": 224.197, "k34": 461.493},
    "C1" : {"k30": 21.690,"k31": 44.238,"k32": 90.409 , "k33": 185.005, "k34": 377.420},
    "C2" : {"k30": 21.260,"k31": 43.379,"k32": 88.691 , "k33": 181.569, "k34": 370.655},
    "C3" : {"k30": 20.831,"k31": 42.520,"k32": 86.973 , "k33": 178.133, "k34": 363.890},
    "C4" : {"k30": 20.401,"k31": 41.661,"k32": 85.255 , "k33": 174.697, "k34": 357.126},
    "C5" : {"k30": 19.972,"k31": 40.845,"k32": 83.537 , "k33": 171.219, "k34": 350.361},
    "C6" : {"k30": 19.488,"k31": 39.965,"k32": 81.819 , "k33": 167.804, "k34": 343.597},
    "C7" : {"k30": 19.048,"k31": 39.138,"k32": 80.101 , "k33": 163.230, "k34": 332.430},
    "C8" : {"k30": 18.372,"k31": 37.506,"k32": 76.557 , "k33": 156.251, "k34": 324.648},
    "C9" : {"k30": 17.502,"k31": 35.863,"k32": 73.121 , "k33": 150.645, "k34": 310.077}
  },
  "GIB": {
    "NA" : {"k30": 23.900,"k31": 50.000,"k32": 101.400, "k33": 208.800, "k34": 429.800},
    "C1" : {"k30": 20.200,"k31": 41.200,"k32": 84.200 , "k33": 172.300, "k34": 351.500},
    "C2" : {"k30": 19.800,"k31": 40.400,"k32": 82.600 , "k33": 169.100, "k34": 345.200},
    "C3" : {"k30": 19.400,"k31": 39.600,"k32": 81.000 , "k33": 165.900, "k34": 338.900},
    "C4" : {"k30": 19.000,"k31": 38.800,"k32": 79.400 , "k33": 162.700, "k34": 332.600},
    "C5" : {"k30": 18.600,"k31": 38.040,"k32": 77.800 , "k33": 159.460, "k34": 326.300},
    "C6" : {"k30": 18.150,"k31": 37.220,"k32": 76.200 , "k33": 156.280, "k34": 320.000},
    "C7" : {"k30": 17.740,"k31": 36.450,"k32": 74.600 , "k33": 152.020, "k34": 309.600},
    "C8" : {"k30": 17.110,"k31": 34.930,"k32": 71.300 , "k33": 145.520, "k34": 302.353},
    "C9" : {"k30": 16.300,"k31": 33.400,"k32": 68.100 , "k33": 140.299, "k34": 288.782}
  }
  };

**Comment by HVNC1** [comment]
this is actual data. ok. there may be some discrepancies, but your reference values are correct. thank you for a good calculation tool
